create table "COMPUTERS" (
  "ID" INTEGER NOT NULL,
  "NAME" VARCHAR NOT NULL,
  "MANUFACTURER_ID" INTEGER NOT NULL
);

create table "COMPANIES" (
  "ID" INTEGER NOT NULL,
  "NAME" VARCHAR NOT NULL
);